title: "Angelo Dian"
description: "PhD Graduate in Experimental Phonetics"
theme: minima
timezone: Australia/Melbourne

# navbar links (this is what minima reads)
header_pages:
  - index.md
  - research.md
  - publications.md
  - cv.md
  - blog.md
  - contact.md

# optional but nice to have
plugins:
  - jekyll-feed
